# Generated by Django 3.0.7 on 2020-10-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='email',
        ),
    ]
