# Generated by Django 3.0.7 on 2020-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20201017_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=20, null=True)),
                ('Phone', models.IntegerField()),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user_table',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_table',
            name='contacts',
            field=models.ManyToManyField(to='newapp.Contacts'),
        ),
    ]
