# Generated by Django 3.0.7 on 2020-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20201017_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='contacts',
            field=models.ManyToManyField(related_name='Contacts', to='newapp.Contacts'),
        ),
    ]
